version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/scraper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "bench"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"